version: "3.1"
services:

  wallet:
    image: tearust/tea-browser-wallet:v0.2.1
    container_name: wallet
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./dist:/www/dist
    ports:
      - 80:80
      - 443:443


  