version: "3.1"
services:

  wallet:
    image: tearust/tea-browser-wallet:0.1.5
    container_name: wallet
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./dist:/www/dist
    ports:
      - 80:80
      - 443:443
  
  facade:
    image: tearust/layer1-facade:2.0.5
    container_name: facade
    restart: always
    environment: 
      - LAYER1_URL=ws://139.198.27.87:9944
      - LAYER1_RPC=http://139.198.27.87:9933
      - ACCOUNT_URI=Alice
      - DUMMY_RA_TIME=6000
      - LOOP_ALL=1800
    command: ["npm", "start"]

  