<template>
  <div class="tea-page">
    <h4>Plant my Camellia</h4>

    <el-steps :active="step" simple>
      <el-step title="Generate"></el-step>
      <el-step title="Fill"></el-step>
      <el-step title="Start mining"></el-step>
    </el-steps>

    <div class="t-step" v-if="step===1">
      <p>Please run the following command on your mining machine running the Ubuntu operating system. More information about software and hardware mining machine requirements are available in <a href="https://github.com/tearust/teaproject/wiki/Mining-With-Your-Own-Hardware#minimum-mining-machine-requirements---os" target="_blank">our mining setup wiki</a>.
</p>
      <div class="c-shell" style="margin-top:0;">
        <p style="font-weight:bold;">
          <span class="js_need_copy1">
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/tearust/delegator-resources/epoch6/gen_tea_id.sh)"
          </span>

          <span title="copy" data-clipboard-target=".js_need_copy1" style="margin-left: 5px; float:right;" class="iconfont tea-icon-btn icon-copy js_copy"></span>
        </p>
      </div>
      <p>After running the command, copy the hex-encoded <strong>machine id</strong> and also the <strong>SSS8 Address</strong> from the mining machine output. Then come back to the mining wallet and click <strong>Next step</strong>.</p>

      <div style="width:80%;">
        <img src="../assets/images/step_1.jpg" />
      </div>

      <div style="display: flex; justify-content: space-between; margin-top: 20px">
        <el-button type="primary" size="small" plain :disabled="true">
          Previous step
        </el-button>
        <el-button type="primary" size="small" @click="step=2">
          Next step
        </el-button>
      </div>

    </div>

    <div v-if="step===2" class="t-step">
      <p>
        Please fill out the form below to generate the shell mining commands. 
        <br/>
        Note that you need <b class="block">1000 TEA</b> available for your initial stake. More info is available <a href="https://github.com/tearust/teaproject/wiki/Mining#mining-machines-are-no-longer-free" class="t-wiki" target="_blank">on our wiki.</a>
      </p>

      <el-form :model="form" label-width="320px" :rules="rules" ref="form" class="tea-modal">
        <el-form-item label="CML ID" prop="cml_id">
          <el-input :disabled="true" v-model="form.cml_id"></el-input>
        </el-form-item>

        <el-form-item label="Machine ID" prop="miner_id">
          <el-input  v-model="form.miner_id" show-word-limit maxlength="66" minlength="66"></el-input>
          <el-button slot="append" icon="el-icon-search"></el-button>

          <TeaIconButton icon_style="font-size:18px;" tip="Autogenerated unique name for your mining machine." icon="questionmark" />
        </el-form-item>

        <el-form-item label="Miner IP" prop="miner_ip">
          <el-input v-model="form.miner_ip"></el-input>

          <TeaIconButton icon_style="font-size:18px;" tip="The IP address of your mining machine. If you are planting a C CML, you can use any random number here. If running Ubuntu, you can find your machine's IP address by running the following from the command line: ip addr show eth0" icon="questionmark" />
        </el-form-item>

        <el-form-item label="Mining machine's Polkadot wallet (SS58) address" prop="account">
          <el-input v-model="form.account"></el-input>

          <TeaIconButton icon_style="font-size:18px;" tip="The Polkadot wallet address created by the mining machine." icon="questionmark" />
        </el-form-item>

        <el-form-item label="Mining stake slot 0 requires TEA">
          <el-input :disabled="true" value="1000"></el-input>
        </el-form-item>

        
      </el-form>

      <div style="display: flex; justify-content: space-between; margin-top: 20px">
        <el-button type="primary" size="small" plain @click="step=1">
          Previous step
        </el-button>
        <el-button type="primary" size="small" @click="generateShell()">
          Next step
        </el-button>
      </div>
    </div>

    <div class="t-step" v-if="step===3">
      <div class="c-shell">
        <p style="font-weight:bold;">
          <span class="js_need_copy">
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/tearust/delegator-resources/epoch6/install.sh)"
          </span>

          <span title="copy" data-clipboard-target=".js_need_copy" style="margin-left: 5px; float:right;" class="iconfont tea-icon-btn icon-copy js_copy"></span>
        </p>
      </div>

      <p style="margin-top:5px;">
        The command above must be run on your mining machine from your terminal application. <br/>
        After the script has completed, you can use the button below to verify the installation. <br/>
        A more in-depth mining hardware setup guide is available on our <a href="https://github.com/tearust/teaproject/wiki/Mining-With-Your-Own-Hardware" target="_blank">Github wiki</a>.
      </p>

      <div style="display: flex; justify-content: space-between; margin-top: 20px">
        <el-button type="primary" size="small" plain @click="step=2">
          Previous step
        </el-button>

        <el-button
          v-if="cml_type==='B'"
          style="padding-left: 25px; padding-right: 25px"
          size="small"
          @click="verifyMiner()"
          type="primary"
        >
          Verify my miner
        </el-button>
        <el-button
          v-if="cml_type!=='B'"
          size="small"
          style="padding-left: 25px; padding-right: 25px"
          @click="testPlant()"
          type="primary"
        >
          Plant
        </el-button>
      </div>
    </div>
    
<p v-if="cml_type==='C'" style="margin-top:5px;">
        C CML seeds aren't able to host TApps. They can earn public service rewards by running <a href="https://github.com/tearust/teaproject/wiki/Mining---Availability-Attestation" target="_blank">Availability Attestation</a> to monitor the availability of B CML mining machines.
      </p> 
      
      
  </div>
</template>
<script>
import Base from "../workflow/Base";
import { _ } from "tearust_utils";
import utils from "../tea/utils";
import { mapGetters } from "vuex";
import ClipboardJS from 'clipboard';
import TeaIconButton from '../components/TeaIconButton';
export default {
  components: {
    TeaIconButton,
  },
  data() {
    return {
      step: 1,
      cml_type: null,
      form: {
        cml_id: null,
        miner_id: null,
        miner_ip: null,
        account: null,
      },
      rules: {
        cml_id: [{ required: true }],
        miner_id: [
          { required: true },
          {
            min: 66,
          },
          {
            max: 66
          }
        ],
        miner_ip: [
          { required: true },
          {
            validator: (rule, val, cb)=>{
              if(this.cml_type === 'B'){
                if(!utils.isValidIP(val)){
                  cb('Invalid ip address');
                }
                else{
                  cb();
                }
              }
              else{
                cb();
              }
              
            }
          }
        ],
        account: [{ required: true }],
      },

      shell: false,
    };
  },
  computed: {
    ...mapGetters(["layer1_account"]),
  },
  async created(){
    this.initCopyEvent();
  },
  beforeDestroy(){
    this.clipboard && this.clipboard.destroy();
  },
  async mounted() {
    this.form.cml_id = this.$route.params.cml_id;

    this.wf = new Base();
    await this.wf.init();

    this.$root.loading(true);

    const layer1_instance = this.wf.getLayer1Instance();
    const api = layer1_instance.getApi();

    let cml = await api.query.cml.cmlStore(this.form.cml_id);
    cml = cml.toJSON();

    // const map = {
    //   A: "cmlAMiningMachineCost",
    //   B: "cmlBMiningMachineCost",
    //   C: "cmlCMiningMachineCost",
    // };

    this.cml_type = cml.intrinsic.cml_type;

    // this.form.miner_id = utils.uuid().replace(/\-/g, '');
    this.$root.loading(false);
  },
  methods: {
    initCopyEvent(){
      const clipboard = new ClipboardJS('.js_copy');
      this.clipboard = clipboard;
      clipboard.on('success', (e)=>{
        e.clearSelection();
        this.$root.success('Copied');
      });

      clipboard.on('error', (e)=>{
      });
    },
    async generateShell() {
      const ref = this.$refs["form"];
      await ref.validate();
      this.step = 3;
    },
    async testPlant() {
      const x = await this.beforeAction();
      if(!x) return false;
      const layer1_instance = this.wf.getLayer1Instance();
      const api = layer1_instance.getApi();

      this.$root.loading(true);
      try {
        const form = this.form;

        // validate tea and coffee balance
        if(this.layer1_account.balance <= 1000){
          throw 'You need 1000 TEA for the first staking slot. You can put up some of your extra <a href="https://github.com/tearust/teaproject/wiki/Genesis-TEA-Loans" target="_blank">CML seeds for a Genesis Loan</a> and receive TEA in return.';
        }
        

        const tx = api.tx.cml.startMining(
          form.cml_id,
          form.miner_id,
          form.account,
          form.miner_ip,
          null,
        );
        await layer1_instance.sendTx(this.layer1_account.address, tx);

        this.$router.push("/login_account");
      } catch (e) {
        this.$root.showError(e);
      }
      this.$root.loading(false);
    },
    async verifyMiner(){
      const x = await this.beforeAction();
      if(!x) return false;
      utils.cache.put('cml_plant_'+this.form.cml_id, this.form);

      const url = `http://${this.form.miner_ip}:8000/verify_deployed?cml=${this.form.cml_id}`;
      window.open(url, '_blank');
    },
    async beforeAction(){
      try{
        const html = 'Check that the command line output lists out all creation steps as <b>done</b>.<br/> Does your mining machine install script show that all creation steps are <b>done</b> and that <b>docker start completed?</b>';
        await this.$confirm(html, {
          dangerouslyUseHTMLString: true,
          confirmButtonText: 'Yes',
          cancelButtonText: 'No - continue to wait',
        });

        return true;
      }catch(e){}
      return false;
    }
  },
};
</script>
<style lang="scss" scoped>
.c-shell {
  padding: 5px 15px;
  margin-top: 20px;
  height: 40px;
  background: #000;
  p {
    color: rgb(2, 250, 35);
    padding: 2px 0;
    margin: 0;
  }
}
.t-step{
  &>p{
    margin: 20px 0 5px;
  }
}
</style>
